- Classes/Utility/GeneralUtility.php
Do not try to access the operator if it does not exist to avoid a
run-time error.
> fix conditions without operator

- Classes/Controller/Form.php
- Classes/Finisher/GenerateAuthCode.php
- Classes/Finisher/Mail.php
- Classes/Finisher/Redirect.php
- Classes/Validator/DefaultValidator.php
A FlexForm is not always available and null may be passed to pi_getFFvalue, which expects an array, from various places. This patch passes [] is no FlexForm is defined and avoids a run-time error.
> always pass array to pi_getFFvalue

- Classes/Mailer/TYPO3Mailer.php
When multiple mails are being sent (e.g. admin, user), TYPO3Mailer currently reuses the MailMessage instance. In effect, fields are not reset and headers such as CC are reused in additional mails.
This patch creates a new MailMessage instance after init is called. The additional initialization of emailObj in __construct is not removed to leave the constructor with the field initialized.
> fix mail message initialization

- Classes/Utility/GeneralUtility.php
Callers of doRedirect, such as `Controller\Form\init()` may pass numeric page ids, such as `$GLOBALS['TSFE']->id` for the page id. Accepting `int|string` fixes errors from these calls.
> Allow numeric page ids in doRedirect

- Classes/Finisher/Mail.php
Use emailSettings to initialize the template file setting, because settings['mode'] is no longer available at this point.
> fix template file setting

- Classes/Controller/Form.php
- Classes/Utility/Globals.php
- Classes/View/AbstractView.php
- pi1/class.tx_formhandler_pi1.php
hello, I would like to use this version of formhandler to update some older TYPO3 Installations. 
There are some old forms and the prefixId is used in the context of "$this->pi_wrapInBaseClass($content)" function, this is used [here](https://github.com/JAK0TA/formhandler/blob/b57d7c340540bdea34b0488db55e5f44d585f089/Classes/View/Form.php#L350) in the render() function. Here the prefixId is converted to a CSS class which is otherwise missing. I think especially for updates of older version this would be good. We used that css class a lot.
Best Regards and thanks for all the work and efforts to make formhandler compatible with TYPO3 11 and PHP8
Sven
> [TASK] bring back the prefixID

- Classes/Controller/Form.php
- Classes/Utility/GeneralUtility.php
Fixes #73 and some PHP Warnings hidden by #73
See:
Undefined array key "alternate" in /var/www/public/typo3conf/ext/formhandler/Classes/Controller/Form.php line 188
> Type and null checks

- Classes/Controller/Form.php
Hi,
if you integrate CSS Files in this way:
```
cssFile {
10 = TEXT
10.value = EXT:my_sitepackage/Resources/Public/Css/ContactForm/File1.css
20 = TEXT
20.value = EXT:my_sitepackage/Resources/Public/Contrib/datepicker/datepicker.css
30 = TEXT
30.value = EXT:my_sitepackage/Resources/Public/Contrib/chosen/chosen.min.css
}
```
you get file paths like this:
`<link rel="stylesheet" href="/var/www/html/public/typo3conf/ext/my_sitepackage/Resources/Public/Css/ContactForm/File1.css" media="all">`
so add a check after resolveRelPathFromSiteRoot() because this is only relevant for css files, resolveRelPathFromSiteRoot() checks also for Template and lang files
> [TASK] allows integration of CSS Files with EXT: syntax

- Classes/Finisher/Mail.php
- Classes/Mailer/MailerInterface.php
- Classes/Mailer/TYPO3Mailer.php
The Symfony Mailers handling for embeds seems to have changed, requiring a name (for a cid) and returning the mail object instead of the cid.
> Fix mail embeds not working

- Classes/Interceptor/RemoveXSS.php
- Classes/Utility/GeneralUtility.php
- Classes/View/Form.php
fixes #116 
htmlspecialchars() by default tries to encode allready encoded characters again. setting "double_encode" to false prevents this.
> Prevent double encoding of special characters

- Classes/Utility/GeneralUtility.php
`###if_` conditions can only check against field- or global values. 
This change would make checking string values like `###if_'teststring' != 'secondTestString'###` possible, which would enable checkign if typoscript or language markers are set. (like `###if_'###ts_marker###' == 'someValue'###`)
> Make string comparisons using ###if_ markers possible

- Classes/Controller/Form.php
- Classes/Validator/ErrorCheck/FileMinCount.php
The FileMinCount validator currently does not work correctly.
One issue is that the validator will not fail even when the min count is set to 1 but no files have been uploaded. In that case the array offset `$files[$this->formFieldName]` does not exist, but the check still passes.
Another problem is that the validators are currently run before the file processing function (which stores the uploaded files in the session). That means that the validators are always working with either no files (in case it's the first submit) or old files (in case it's a subsequent submit).
> Fix file validators not working correctly

- Classes/Controller/FormController.php
- Classes/Validator/DefaultValidator.php
- "back"-buttons currently dont work right. Clicking one on the last form step still submits the form.
- The default validator returned the wrong results, thus still passing even when there are errors
> Fix step back not working & validator returning wrong result

- Classes/Utility/Utility.php
The Mailfinisher can currently throw errors when at least one of the rootpaths (template, layout or partial) isnt set. This change guarantees that the array keys at least exist
> Fix rootpath key not set

- Classes/Finisher/MailFinisher.php
The mailfinisher aborted too early in case there were only email adresses (and no fields) given
> Fix email not beeing sent

- Classes/Finisher/MailFinisher.php
This adds the ability to use markers like `{1.group.field}` in the subject line
> Mailfinisher: Add ability to use markers in subject line

- Classes/Finisher/MailFinisher.php
`GeneralUtility::validEmail()` doesnt handle whitespace trimming. Emails with whitespaces like ` test@test.com` currently wont work because of that
> Fix multiple reciever emails not working sometimes

- Classes/Controller/Form.php
SIngle-file uploads kept failing because checks if arrays/array keys really exists are missing.
> Fix fileupload failing

- Classes/Validator/ErrorCheck/FileRequired.php
There were no checks if specific array keys exist before accessing them, thus errors were beeing thrown
> Fix filerequired validator not working

- Classes/Controller/FormController.php
- Classes/Domain/Model/Config/FormModel.php
- Classes/Domain/Model/Config/Interceptor/TurnstileCaptchaInterceptorModel.php
- Classes/Http/TurnstileVerifyRequester.php
- Classes/Interceptor/AbstractInterceptor.php
- Classes/Interceptor/TurnstileCaptchaInterceptor.php
- Classes/ViewHelpers/GetTurnstileSitekeyViewHelper.php
- Resources/Private/Language/locallang_example_form.xlf
- Resources/Private/Partials/FormField/TurnstileCaptchaField.html
Adds a turnstile captcha interceptor and example field.
Additional changes:
- saveInterceptors can now fail, setting a formerror.
- the formconfig now has a captchaFieldValues property, containing all captcha responses. (Should make adding new captchas like recaptcha easier)
> Add turnstile interceptor

- Classes/Controller/FormController.php
Currently the JSON response step value gets set before `formStepChange()` is called. Thus the step value allways lags one submit behind
> Fix wrong step value in json

- Classes/View/Form.php
Adds a new `###aria_is_invalid_(fieldname)###` marker, which depending on if a field has an error adds an `aria-invalid="true"` attribute
> Add new ###aria_is_invalid### marker
